version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb+srv://nikno8:Teacod0407%40@atlascluster.kmkungw.mongodb.net/"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: nikno8
      MONGO_INITDB_ROOT_PASSWORD: Teacod0407@
    ports:
      - "27017:27017"
